### PR TITLE
enhanced navigation bar

### PR DESCRIPTION
**Pull request by naina24**
Solved Issue #6
Description: Enhanced navigation bar 
Here, the screenshot attached
Screenshot

### CODE REVIEW

**Review by priyanshu0405 — CHANGES_REQUESTED** [review]
Hey @naina24, looks good to me. Just one thing if you could change the position and on:hover effect to something like this:  https://jiitodc.netlify.app/
Github repo for referance - https://github.com/JIITODC/jiitodc.github.io

**Comment by naina24** [comment]
Yes, I can try for this

**Comment by naina24** [comment]
I am trying to deploy but page not found error getting

**Comment by naina24** [comment]
I am trying to deploy site on netlify but page not found error getting

**Comment by priyanshu0405** [comment]
@naina24, the site was earlier deployed on vercel but as I shifted the repo to Geekhaven the git integration stopped. I am currently working on that. Hosting it on netlify.

**Comment by naina24** [comment]
So how can I show you what I have done

**Pull request closed without merging**
